In [1]:
#Libs

import pandas as pd
import numpy as np

#libs gráficas
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

#Avisos
import warnings
warnings.filterwarnings('ignore')

In [2]:
uf = pd.read_csv('br_inep_avaliacao_alfabetizacao_uf.csv')
uf.head()

,ano,sigla_uf,serie,rede,taxa_alfabetizacao,media_portugues,proporcao_aluno_nivel_0,proporcao_aluno_nivel_1,proporcao_aluno_nivel_2,proporcao_aluno_nivel_3,proporcao_aluno_nivel_4,proporcao_aluno_nivel_5,proporcao_aluno_nivel_6,proporcao_aluno_nivel_7,proporcao_aluno_nivel_8
0,2023,AM,2,3,49.20,733.6637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,PB,2,2,55.23,744.8152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,PR,2,5,73.12,757.2146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,AP,2,3,41.87,732.7858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,PE,2,5,58.95,747.4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
uf.shape

(145, 15)

In [20]:
uf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      145 non-null    int64
 1   sigla_uf                 145 non-null    object
 2   serie                    145 non-null    int64
 3   rede                     145 non-null    int64
 4   taxa_alfabetizacao       145 non-null    float64
 5   media_portugues          145 non-null    float64
 6   proporcao_aluno_nivel_0  75 non-null     float64
 7   proporcao_aluno_nivel_1  75 non-null     float64
 8   proporcao_aluno_nivel_2  75 non-null     float64
 9   proporcao_aluno_nivel_3  75 non-null     float64
 10  proporcao_aluno_nivel_4  75 non-null     float64
 11  proporcao_aluno_nivel_5  75 non-null     float64
 12  proporcao_aluno_nivel_6  75 non-null     float64
 13  proporcao_aluno_nivel_7  75 non-null     float64
 14  proporcao_aluno_nivel_8  75 non-null     float64
dtypes: float64(11), int64(3), object(1)
memory usage: 17.1+ KB

In [15]:
# Definir as colunas chave
colunas_chave = ["ano", "sigla_uf"]

# 1. Verificar se existem duplicados considerando apenas as chaves
tem_duplicados = uf.duplicated(subset=colunas_chave).any()
print(f"O CSV possui dados duplicados para a combinação de Ano e UF? {'Sim' if tem_duplicados else 'Não'}")

# 2. Contar a quantidade de linhas duplicadas com base nessas chaves
total_duplicados = uf.duplicated(subset=colunas_chave).sum()
print(f"Quantidade de registros duplicados para Ano e UF: {total_duplicados}")

O CSV possui dados duplicados para a combinação de Ano e UF? Sim
Quantidade de registros duplicados para Ano e UF: 96

In [21]:
# Conta os valores vazios em cada coluna do DataFrame uf
vazios_por_coluna_uf = uf.isna().sum()
print("Células vazias por coluna no DataFrame 'uf':")
print(vazios_por_coluna_uf)

Células vazias por coluna no DataFrame 'uf':
ano                         0
sigla_uf                    0
serie                       0
rede                        0
taxa_alfabetizacao          0
media_portugues             0
proporcao_aluno_nivel_0    70
proporcao_aluno_nivel_1    70
proporcao_aluno_nivel_2    70
proporcao_aluno_nivel_3    70
proporcao_aluno_nivel_4    70
proporcao_aluno_nivel_5    70
proporcao_aluno_nivel_6    70
proporcao_aluno_nivel_7    70
proporcao_aluno_nivel_8    70
dtype: int64

In [6]:
municipios = pd.read_csv('br_inep_avaliacao_alfabetizacao_municipio.csv')
uf.head()

,ano,sigla_uf,serie,rede,taxa_alfabetizacao,media_portugues,proporcao_aluno_nivel_0,proporcao_aluno_nivel_1,proporcao_aluno_nivel_2,proporcao_aluno_nivel_3,proporcao_aluno_nivel_4,proporcao_aluno_nivel_5,proporcao_aluno_nivel_6,proporcao_aluno_nivel_7,proporcao_aluno_nivel_8
0,2023,AM,2,3,49.20,733.6637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,PB,2,2,55.23,744.8152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,PR,2,5,73.12,757.2146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023,AP,2,3,41.87,732.7858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,PE,2,5,58.95,747.4522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
municipios.shape

(23995, 15)

In [8]:
municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23995 entries, 0 to 23994
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      23995 non-null  int64
 1   id_municipio             23995 non-null  int64
 2   serie                    23995 non-null  int64
 3   rede                     23995 non-null  int64
 4   taxa_alfabetizacao       23995 non-null  float64
 5   media_portugues          23995 non-null  float64
 6   proporcao_aluno_nivel_0  12448 non-null  float64
 7   proporcao_aluno_nivel_1  12448 non-null  float64
 8   proporcao_aluno_nivel_2  12448 non-null  float64
 9   proporcao_aluno_nivel_3  12448 non-null  float64
 10  proporcao_aluno_nivel_4  12448 non-null  float64
 11  proporcao_aluno_nivel_5  12448 non-null  float64
 12  proporcao_aluno_nivel_6  12448 non-null  float64
 13  proporcao_aluno_nivel_7  12448 non-null  float64
 14  proporcao_aluno_nivel_8  12448 non-null  float64
dtypes: float64(11), int64(4)
memory usage: 2.7 MB

In [9]:
municipios.isnull().sum().sum()

np.int64(103923)

In [17]:
# Definir as colunas chave para o município
colunas_chave_mun = ["ano", "id_municipio"]

# 1. Verificar se existem duplicados considerando apenas as chaves
tem_duplicados_mun = municipios.duplicated(subset=colunas_chave_mun).any()
print(f"O DataFrame municipio possui dados duplicados para a combinação de Ano e ID Município? {'Sim' if tem_duplicados_mun else 'Não'}")

# 2. Contar a quantidade de linhas duplicadas com base nessas chaves
total_duplicados_mun = municipios.duplicated(subset=colunas_chave_mun).sum()
print(f"Quantidade de registros duplicados para Ano e ID Município: {total_duplicados_mun}")

O DataFrame municipio possui dados duplicados para a combinação de Ano e ID Município? Sim
Quantidade de registros duplicados para Ano e ID Município: 12965

In [11]:
meta_brasil = pd.read_csv('br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_brasil.csv')
meta_brasil.head()

,ano,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2025,Pública,66.0,60.0,64.00,67.00,71.00,74.00,77.00,80,88.00
1,2024,Pública,59.2,59.9,63.77,67.47,70.97,74.23,77.24,80,87.37
2,2023,Pública,55.9,59.9,63.77,67.47,70.97,74.23,77.24,80,86.00

In [12]:
meta_brasil.shape

(3, 11)

In [13]:
meta_brasil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      3 non-null      int64
 1   rede                     3 non-null      object
 2   taxa_alfabetizacao       3 non-null      float64
 3   meta_alfabetizacao_2024  3 non-null      float64
 4   meta_alfabetizacao_2025  3 non-null      float64
 5   meta_alfabetizacao_2026  3 non-null      float64
 6   meta_alfabetizacao_2027  3 non-null      float64
 7   meta_alfabetizacao_2028  3 non-null      float64
 8   meta_alfabetizacao_2029  3 non-null      float64
 9   meta_alfabetizacao_2030  3 non-null      int64
 10  percentual_participacao  3 non-null      float64
dtypes: float64(8), int64(2), object(1)
memory usage: 396.0+ bytes

In [14]:
# 2. Verificar se existem linhas duplicadas (Retorna True ou False)
tem_duplicados = meta_brasil.duplicated().any()
print(f"O CSV possui dados duplicados? {'Sim' if tem_duplicados else 'Não'}")

# 3. Contar a quantidade total de linhas duplicadas
total_duplicados = meta_brasil.duplicated().sum()
print(f"Quantidade de linhas totalmente duplicadas: {total_duplicados}")

O CSV possui dados duplicados? Não
Quantidade de linhas totalmente duplicadas: 0

In [16]:
meta_municipio = pd.read_csv('br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_municipio.csv')
meta_municipio.head()

,ano,id_municipio,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,nivel_alfabetizacao,percentual_participacao
0,2023,4301750,Municipal,NaN,NaN,14.05,23.65,37.00,52.68,67.85,80,NaN,NaN
1,2024,4301750,Municipal,4.40,NaN,14.05,23.65,37.00,52.68,67.85,80,0.0,92.59
2,2024,2406908,Municipal,42.86,7.94,14.05,23.65,37.00,52.68,67.85,80,1.0,84.00
3,2023,2406908,Municipal,4.40,7.94,14.05,23.65,37.00,52.68,67.85,80,0.0,82.14
4,2023,1718501,Municipal,4.60,8.25,14.48,24.16,37.49,53.03,68.00,80,0.0,95.65

In [17]:
meta_municipio.shape

(10704, 13)

In [18]:
meta_municipio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10704 entries, 0 to 10703
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      10704 non-null  int64
 1   id_municipio             10704 non-null  int64
 2   rede                     10704 non-null  object
 3   taxa_alfabetizacao       10584 non-null  float64
 4   meta_alfabetizacao_2024  10464 non-null  float64
 5   meta_alfabetizacao_2025  10704 non-null  float64
 6   meta_alfabetizacao_2026  10704 non-null  float64
 7   meta_alfabetizacao_2027  10704 non-null  float64
 8   meta_alfabetizacao_2028  10704 non-null  float64
 9   meta_alfabetizacao_2029  10704 non-null  float64
 10  meta_alfabetizacao_2030  10704 non-null  int64
 11  nivel_alfabetizacao      10584 non-null  float64
 12  percentual_participacao  10584 non-null  float64
dtypes: float64(9), int64(3), object(1)
memory usage: 1.1+ MB

In [19]:
meta_uf = pd.read_csv('br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_uf.csv')
meta_uf.head()

,ano,sigla_uf,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2024,RR,Pública,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023,RR,Pública,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,AC,Pública,NaN,NaN,56.9,62.2,67.3,72.0,76.2,80.0,NaN
3,2024,AC,Pública,51.38,NaN,56.9,62.2,67.3,72.0,76.2,80.0,80.87
4,2023,DF,Pública,NaN,NaN,63.1,67.0,70.6,74.0,77.1,80.0,NaN

In [20]:
meta_uf.shape

(54, 12)

In [21]:
meta_uf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      54 non-null     int64
 1   sigla_uf                 54 non-null     object
 2   rede                     54 non-null     object
 3   taxa_alfabetizacao       50 non-null     float64
 4   meta_alfabetizacao_2024  48 non-null     float64
 5   meta_alfabetizacao_2025  52 non-null     float64
 6   meta_alfabetizacao_2026  52 non-null     float64
 7   meta_alfabetizacao_2027  52 non-null     float64
 8   meta_alfabetizacao_2028  52 non-null     float64
 9   meta_alfabetizacao_2029  52 non-null     float64
 10  meta_alfabetizacao_2030  52 non-null     float64
 11  percentual_participacao  50 non-null     float64
dtypes: float64(9), int64(1), object(2)
memory usage: 5.2+ KB

In [26]:
aluno_2023 = pd.read_csv('TS_ALUNO_2023.csv', encoding='latin1', sep=';')
aluno_2023.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2023,11,RO,11008701,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
1,2023,11,RO,11008695,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,714.314857,0
2,2023,11,RO,11008687,2,60000001,3,1100205,Porto Velho,0,0,17,NaN,NaN,0
3,2023,11,RO,11008682,2,60000001,3,1100205,Porto Velho,1,1,17,1.045465,759.206313,1
4,2023,11,RO,11008729,2,60000001,3,1100205,Porto Velho,0,0,19,NaN,NaN,0

In [27]:
aluno_2023.shape

(1747439, 15)

In [28]:
aluno_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1747439 entries, 0 to 1747438
Data columns (total 15 columns):
 #   Column               Dtype
---  ------               -----
 0   NU_ANO_AVALIACAO     int64
 1   CO_UF                int64
 2   SG_UF                object
 3   ID_ALUNO             int64
 4   TP_SERIE             int64
 5   ID_ESCOLA            int64
 6   TP_DEPENDENCIA       int64
 7   CO_MUNICIPIO         int64
 8   NO_MUNICIPIO         object
 9   IN_PRESENCA_LP       int64
 10  IN_PREENCHIMENTO_LP  int64
 11  CO_CADERNO_LP        int64
 12  VL_PESO_ALUNO_LP     float64
 13  VL_PROFICIENCIA_LP   float64
 14  IN_ALFABETIZADO      int64
dtypes: float64(2), int64(11), object(2)
memory usage: 200.0+ MB

In [22]:
aluno_2024 = pd.read_csv('TS_ALUNO_2024.csv', encoding='latin1', sep=';')
aluno_2024.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,IN_PREENCHIMENTO_LP,CO_CADERNO_LP,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2024,11,RO,11022231,2,60000163,3,1100015,Alta Floresta D'Oeste,1,1,1,1.06,759.43,1
1,2024,11,RO,11019498,2,60000164,3,1100015,Alta Floresta D'Oeste,1,1,10,1.00,741.28,0
2,2024,11,RO,11019621,2,60000334,3,1100015,Alta Floresta D'Oeste,1,1,9,1.13,807.04,1
3,2024,11,RO,11019638,2,60000334,3,1100015,Alta Floresta D'Oeste,1,1,19,1.09,730.96,0
4,2024,11,RO,11019694,2,60000379,3,1100015,Alta Floresta D'Oeste,1,1,8,1.11,735.46,0

In [23]:
aluno_2024.shape

(2120560, 15)

In [24]:
aluno_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2120560 entries, 0 to 2120559
Data columns (total 15 columns):
 #   Column               Dtype
---  ------               -----
 0   NU_ANO_AVALIACAO     int64
 1   CO_UF                int64
 2   SG_UF                object
 3   ID_ALUNO             int64
 4   TP_SERIE             int64
 5   ID_ESCOLA            int64
 6   TP_DEPENDENCIA       int64
 7   CO_MUNICIPIO         int64
 8   NO_MUNICIPIO         object
 9   IN_PRESENCA_LP       int64
 10  IN_PREENCHIMENTO_LP  int64
 11  CO_CADERNO_LP        int64
 12  VL_PESO_ALUNO_LP     float64
 13  VL_PROFICIENCIA_LP   float64
 14  IN_ALFABETIZADO      int64
dtypes: float64(2), int64(11), object(2)
memory usage: 242.7+ MB

In [25]:
aluno_2025 = pd.read_csv('TS_ALUNO_2025.csv', encoding='latin1', sep=';')
aluno_2025.head()

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,...,TX_GABARITO_BLOCO_2,CO_BLOCO_3,TX_RESPOSTA_BLOCO_3,TX_GABARITO_BLOCO_3,CO_BLOCO_4,TX_RESPOSTA_BLOCO_4,TX_GABARITO_BLOCO_4,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO
0,2025,11,RO,11000677,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,BADA,6.0,BBCD,ABCB,NaN,NaN,NaN,1.5,781.776332,1
1,2025,11,RO,11000678,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,BADA,6.0,DACB,ABCB,NaN,NaN,NaN,1.5,717.877346,0
2,2025,11,RO,11000679,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,ABDA,7.0,BBBB,ABBD,NaN,NaN,NaN,1.5,657.836805,0
3,2025,11,RO,11000680,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,BACB,5.0,CABA,ABDA,NaN,NaN,NaN,1.5,765.290294,1
4,2025,11,RO,11000681,2,60000060.0,3.0,1100023.0,Ariquemes,1,...,ABCB,8.0,CABA,CABA,NaN,NaN,NaN,1.5,835.506362,1

In [26]:
aluno_2025.shape

(2222792, 27)

In [27]:
aluno_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2222792 entries, 0 to 2222791
Data columns (total 27 columns):
 #   Column               Dtype
---  ------               -----
 0   NU_ANO_AVALIACAO     int64
 1   CO_UF                int64
 2   SG_UF                object
 3   ID_ALUNO             int64
 4   TP_SERIE             int64
 5   ID_ESCOLA            float64
 6   TP_DEPENDENCIA       float64
 7   CO_MUNICIPIO         float64
 8   NO_MUNICIPIO         object
 9   IN_PRESENCA_LP       int64
 10  IN_PREENCHIMENTO_LP  int64
 11  CO_CADERNO_LP        int64
 12  CO_BLOCO_1           float64
 13  TX_RESPOSTA_BLOCO_1  object
 14  TX_GABARITO_BLOCO_1  object
 15  CO_BLOCO_2           float64
 16  TX_RESPOSTA_BLOCO_2  object
 17  TX_GABARITO_BLOCO_2  object
 18  CO_BLOCO_3           float64
 19  TX_RESPOSTA_BLOCO_3  object
 20  TX_GABARITO_BLOCO_3  object
 21  CO_BLOCO_4           float64
 22  TX_RESPOSTA_BLOCO_4  object
 23  TX_GABARITO_BLOCO_4  object
 24  VL_PESO_ALUNO_LP     float64
 25  VL_PROFICIENCIA_LP   float64
 26  IN_ALFABETIZADO      int64
dtypes: float64(9), int64(8), object(10)
memory usage: 457.9+ MB